ElegantChildren/FrontEnd

- catch-culture-frontend/src/Layout.css
- catch-culture-frontend/src/Layout.jsx
- catch-culture-frontend/src/components/NavBar.css
- catch-culture-frontend/src/components/NavBar.jsx
- catch-culture-frontend/src/router.jsx
미완성
Layout, NavBar 생성
css/파일구조 정리 필요
branch 유지
> Create: Layout, NavBar 생성 미완성

- catch-culture-frontend/src/components/Backitem.jsx
- catch-culture-frontend/src/components/ReviewCard/ReviewCard.jsx
- catch-culture-frontend/src/pages/mypage/BookmarkList.css
- catch-culture-frontend/src/pages/mypage/BookmarkList.jsx
- catch-culture-frontend/src/pages/mypage/LikeList.jsx
- catch-culture-frontend/src/pages/mypage/Mypage.css
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.css
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
- catch-culture-frontend/src/pages/mypage/Visited.jsx
> feat : 리뷰 목록 카드 디자인 및 방문 내역, 북마크, 좋아요 목록 디자인 틀 구현

- catch-culture-frontend/package-lock.json
- catch-culture-frontend/package.json
- catch-culture-frontend/src/api/axios.js
- catch-culture-frontend/src/components/Backitem.jsx
- catch-culture-frontend/src/pages/mypage/Mypage.css
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/search/Search.jsx
- catch-culture-frontend/src/setupProxy.js
position : absolute에서 relative로 수정
> feat : 메인 Mypage 디자인(?) 수정

- catch-culture-frontend/src/components/ReviewCard/ReviewCard.jsx
- catch-culture-frontend/src/pages/mypage/BookmarkList.css
- catch-culture-frontend/src/pages/mypage/BookmarkList.jsx
- catch-culture-frontend/src/pages/mypage/LikeList.jsx
- catch-culture-frontend/src/pages/mypage/Mypage.css
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/Notify.jsx
- catch-culture-frontend/src/pages/mypage/ProfileDetail.css
- catch-culture-frontend/src/pages/mypage/ProfileDetail.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.css
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
- catch-culture-frontend/src/pages/mypage/Visited.jsx
patch는 api 연동 어떻게 하는지 몰라서 공부하고 넣을게유
> [FE] feat : 개인정보 수정 페이지 디자인 및 몇몇 페이지 css 세부 수정

- catch-culture-frontend/src/pages/login/Login.css
- catch-culture-frontend/src/pages/login/Login.jsx
- catch-culture-frontend/src/pages/mypage/BookmarkList.css
- catch-culture-frontend/src/pages/mypage/BookmarkList.jsx
- catch-culture-frontend/src/pages/mypage/LikeList.jsx
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/ProfileDetail.css
- catch-culture-frontend/src/pages/mypage/ProfileDetail.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.css
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
- catch-culture-frontend/src/pages/mypage/Visited.jsx
> [FE] feat : 로그인 페이지 css 수정 및 개인 정보 페이지 patch 메소드 제외 구현 완료

- catch-culture-frontend/src/pages/login/Login.css
- catch-culture-frontend/src/pages/login/Login.jsx
- catch-culture-frontend/src/pages/mypage/BookmarkList.css
- catch-culture-frontend/src/pages/mypage/BookmarkList.jsx
- catch-culture-frontend/src/pages/mypage/LikeList.jsx
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/ProfileDetail.css
- catch-culture-frontend/src/pages/mypage/ProfileDetail.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.css
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
- catch-culture-frontend/src/pages/mypage/Visited.jsx
Reverts ElegantChildren/FrontEnd#37
> Revert "[FE] feat : 로그인 페이지 css 수정 및 개인 정보 페이지 patch 메소드 제외 구현 완료"

- catch-culture-frontend/src/pages/mypage/BookmarkList.css
- catch-culture-frontend/src/pages/mypage/ProfileDetail.css
- catch-culture-frontend/src/pages/mypage/Reviews.css
> feat : 컴포넌트에 맞게 css 세부 수정

- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/router.jsx
> [FE] feat : 공지 -> 제보 라우터 수정

- catch-culture-frontend/src/components/search/noResult/NoBookmarks.jsx
- catch-culture-frontend/src/components/search/noResult/NoLikes.jsx
- catch-culture-frontend/src/components/search/noResult/NoPointHistory.jsx
- catch-culture-frontend/src/components/search/noResult/NoReviews.jsx
- catch-culture-frontend/src/components/search/noResult/NoVisits.jsx
- catch-culture-frontend/src/pages/mypage/BookmarkList.jsx
- catch-culture-frontend/src/pages/mypage/LikeList.jsx
- catch-culture-frontend/src/pages/mypage/PointHistory.css
- catch-culture-frontend/src/pages/mypage/PointHistory.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
- catch-culture-frontend/src/pages/mypage/Visited.jsx
포인트 내역 아직 api 없음
결과 없음 페이지는 페이지마다 설명과 아이콘 다른 게 좋을 듯 하여 컴포넌트에 따로 제작(?)함
> [FE] feat : 포인트 내역 페이지 디자인 및 결과 없음 컴포넌트 디자인

- catch-culture-frontend/src/components/search/noResult/NoBookmarks.jsx
- catch-culture-frontend/src/components/search/noResult/NoLikes.jsx
- catch-culture-frontend/src/components/search/noResult/NoPointHistory.jsx
- catch-culture-frontend/src/components/search/noResult/NoReport.jsx
- catch-culture-frontend/src/components/search/noResult/NoReviews.jsx
- catch-culture-frontend/src/components/search/noResult/NoVisits.jsx
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/ReportList.css
- catch-culture-frontend/src/pages/mypage/ReportList.jsx
- catch-culture-frontend/src/router.jsx
현재 스웨거에 있는 api 중 남은 거 patch 닉네임
필요한 api가 많다...
관리자 페이지 구현하고 있을게
> [FE] feat : 제보 리스트 페이지 디자인 완료

- catch-culture-frontend/src/pages/admin/Admin.jsx
- catch-culture-frontend/src/pages/mypage/BookmarkList.css
- catch-culture-frontend/src/pages/mypage/Mypage.css
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.css
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
- catch-culture-frontend/src/router.jsx
근데 이거 이게 맞나
그리고 마이페이지.jsx에서 isadmin true로 바꿔줘야 관리자 페이지 나옴 false하면 그냥 일반 사용자 마이페이지로 뜨게 함
> [FE] feat : 관리자 페이지 디자인 완료

- catch-culture-frontend/src/pages/mypage/Mypage.jsx
> [FE] feat : 마이페이지 로고 수정

- catch-culture-frontend/src/pages/admin/Admin.jsx
- catch-culture-frontend/src/pages/mypage/Mypage.css
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/PointLevel.css
- catch-culture-frontend/src/pages/mypage/PointLevel.jsx
- catch-culture-frontend/src/pages/mypage/ProfileDetail.jsx
- catch-culture-frontend/src/pages/mypage/ReportList.css
포인트 레벨 페이지 원래 걍 사진 붙여넣었었던 거 코드 구현으로 변경함
patch 끝나면 사용자 프로필 변경 post formDatd 공부하고 할 예정
필요한 api
탈퇴, 제보 목록 api, 리뷰 목록 api, 포인트 내역 api
> [FE] feat : 포인트 레벨 페이지 설명 부분 구현 완 | 닉네임 patch api 구현 중

- catch-culture-frontend/src/components/search/searchBox/SearchBox.jsx
- catch-culture-frontend/src/components/search/searchBox/style.jsx
- catch-culture-frontend/src/pages/search/Search.jsx
- 메인 페이지에서 검색어 전달 구현
- 검색 페이지 API 연결 완료
> Feat: 검색 페이지 - 검색 API 연결

- catch-culture-frontend/package-lock.json
- catch-culture-frontend/package.json
- catch-culture-frontend/src/components/search/noResult/NoVisits.jsx
- catch-culture-frontend/src/pages/admin/Admin.css
- catch-culture-frontend/src/pages/admin/Admin.jsx
- catch-culture-frontend/src/pages/admin/ReportAuthList.jsx
- catch-culture-frontend/src/pages/admin/VisitAuthList.css
- catch-culture-frontend/src/pages/admin/VisitAuthList.jsx
- catch-culture-frontend/src/router.jsx
api 아직 놉
id 별 제보 상세 페이지. 인증 상세 페이지 구현해야 함
> Feat : 관리자 제보, 방문 인증 리스트 페이지 디자인 완

- catch-culture-frontend/src/pages/admin/AdminReport.css
- catch-culture-frontend/src/pages/admin/AdminReport.jsx
- catch-culture-frontend/src/pages/admin/AdminVisit.jsx
- catch-culture-frontend/src/pages/admin/ReportAuthList.jsx
- catch-culture-frontend/src/pages/admin/VisitAuthList.css
- catch-culture-frontend/src/pages/admin/VisitAuthList.jsx
- catch-culture-frontend/src/pages/mypage/PointLevel.css
- catch-culture-frontend/src/router.jsx
제보 페이지 post api 연동 제외 구현 완료
방문 인증 리스트 페이지 구현 완료
방문 인증 상세 페이지 현재 데이터 없어서 보류 중
(VisitAuth api 없어서 현재 데이터 생성 불가)
> Feat : 관리자 페이지 구현 중

- catch-culture-frontend/src/components/NavBar.jsx
- catch-culture-frontend/src/pages/reportPage/report2/Report2.jsx
- catch-culture-frontend/src/pages/reportPage/report2/style.jsx
[제보하기 페이지]
- 카테고리 선택 항목 추가
- 테스트용 console.log 삭제
- warnning 해결
> Feat: 제보하기 페이지 - 카테고리 선택 항목 추가

- catch-culture-frontend/.env
- catch-culture-frontend/src/pages/admin/AdminReport.css
- catch-culture-frontend/src/pages/admin/AdminReport.jsx
- catch-culture-frontend/src/pages/admin/AdminVisit.jsx
- catch-culture-frontend/src/pages/admin/VisitAuthList.css
> Fix : 관리자 페이지 제보 부분 구현 중

- catch-culture-frontend/src/pages/mypage/PointHistory.css
- catch-culture-frontend/src/pages/mypage/PointHistory.jsx
포인트 내역 페이지 구현 완료
근데 이제 백엔드에서 지급인지 차감인지 isGet boolean 데이터 타입으로 만들어달라고 해야 함
> Fix : 포인트 내역 api 연동 완료

- catch-culture-frontend/src/pages/mypage/pointpage/PointUsage.css
- catch-culture-frontend/src/pages/mypage/pointpage/PointUsage.jsx
아직 구매에 따른 포인트 수정 api는 만들어지지 않았음
> Fix : 포인트 사용처 페이지 api 연동 완료

- catch-culture-frontend/src/pages/admin/Admin.css
- catch-culture-frontend/src/pages/mypage/Mypage.css
- catch-culture-frontend/src/pages/mypage/Mypage.jsx
- catch-culture-frontend/src/pages/mypage/ReportList.css
- catch-culture-frontend/src/pages/mypage/ReportList.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.css
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
> Fix : 리뷰내역, 제보하기 목록 api 연동

- catch-culture-frontend/src/pages/mypage/LikeList.jsx
- catch-culture-frontend/src/pages/mypage/PointHistory.jsx
- catch-culture-frontend/src/pages/mypage/ReportList.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
근데 마이페이지 좋아요 목록, 북마크 목록, 방문 인증 목록 좀 이상함 페이지네이션 없이 걍 모든 데이터를 줌
> Feat : 마이페이지 쪽 페이지 별 무한 스크롤 구현

- catch-culture-frontend/src/pages/admin/AdminReport.css
- catch-culture-frontend/src/pages/admin/ReportAuthList.jsx
- catch-culture-frontend/src/pages/admin/VisitAuthList.jsx
- catch-culture-frontend/src/pages/mypage/BookmarkList.css
- catch-culture-frontend/src/pages/mypage/PointHistory.jsx
- catch-culture-frontend/src/pages/mypage/ReportList.css
- catch-culture-frontend/src/pages/mypage/ReportList.jsx
- catch-culture-frontend/src/pages/mypage/Reviews.css
- catch-culture-frontend/src/pages/mypage/Reviews.jsx
- catch-culture-frontend/src/pages/mypage/Visited.jsx
- catch-culture-frontend/src/pages/reportPage/report1/Report1.jsx
검토 거의 다 끝났고 관리자 페이지 쪽 무한 스크롤 구현 중
아직 관리자 페이지 방문 인증 put api도 백에서 아직 구현 안 됐음
> Fix : 스크롤, 정렬 몇몇 디자인

- catch-culture-frontend/package-lock.json
- catch-culture-frontend/package.json
- catch-culture-frontend/src/pages/admin/AdminVisit.jsx
- catch-culture-frontend/src/pages/admin/ReportAuthList.jsx
- catch-culture-frontend/src/pages/admin/VisitAuthList.jsx
- catch-culture-frontend/src/pages/mypage/pointpage/PointUsage.jsx
- catch-culture-frontend/src/pages/reportPage/report3/Report3.jsx
+관리자 페이지 현재 구현 중인 것 : 방문 인증 put api 현재 오류는 안 뜨며 곧 확인 및 수정 예정
+ 유진아 report3 에서 완료 누르면 리다이렉트 되는 페이지 제보 목록 페이지로 바꿨어
+ 사용자 쪽에서 제보 목록 무한 스크롤 다시 해보니 안 됨 수정 예정
+ 관리자 페이지 쪽 api 호출 예외 처리 완료 됐으며 나머지 쪽 오늘 밤에 확인 및 코드 수정 예정
> Feat : 관리자 관련 페이지 무한 스크롤 구현 완

- catch-culture-frontend/src/pages/admin/Admin.jsx
- catch-culture-frontend/src/pages/admin/AdminReport.jsx
- catch-culture-frontend/src/pages/admin/AdminVisit.jsx
- catch-culture-frontend/src/pages/admin/ReportAuthList.jsx
- catch-culture-frontend/src/pages/admin/VisitAuthList.jsx
- catch-culture-frontend/src/pages/mypage/PointHistory.jsx
- catch-culture-frontend/src/pages/mypage/pointpage/PointUsage.jsx
> Fix : Jd 함수 아님 오류 수정

- catch-culture-frontend/src/pages/admin/ReportAuthList.jsx
- catch-culture-frontend/src/pages/admin/VisitAuthList.jsx
- catch-culture-frontend/src/pages/mypage/ReportList.jsx
> Fix : data 오류 다시 시도

- catch-culture-frontend/src/pages/admin/AdminReport.jsx
- catch-culture-frontend/src/pages/login/Login.css
> Fix : 로그인 css 수정 및 params 수정
